### ISSUE TITLE
interesting work, but a small mistake of notation in the paper

### ISSUE THREAD

**Issue by ValarChen** [marblet/GCNmf#1]
By the settings of paper(chapter 3.1 and 4.1), ***X*** is D-dimensional, and **X** is N*D-dimensional.
But ***X***<sub>ij</sub> is used, which I suppose should be **X**<sub>ij</sub>?

**Comment by marblet** [comment]
I think notations are consistent in the paper.
We unify **X** as a matrix, _**X**_ as a vector, _X_ as an element.
In this setting, the element of feature j that node i has should be _Xij_.
Thank you.

**Comment by ValarChen** [comment]
oops, you're right. I mistake it.
This issue can get closd.
